name: infra-pr

on:
  pull_request:
    branches:
      - main
    paths:
      - 'infra/terraform/**'
      - '.github/workflows/infra-*.yml'

env:
  AWS_REGION: "us-west-2"

jobs:
  plan:
    permissions:
      id-token: write
      contents: read
      pull-requests: write 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ vars.AWS_ROLE_TO_ASSUME }}

      - name: Create backend.tf
        run: |
          cat <<EOF > ./infra/terraform/backend.tf
          terraform {
            backend "s3" {}
          }
          EOF
    
      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="bucket=${{ vars.TF_STATE_BUCKET }}" \
            -backend-config="key=${{ github.repository }}/terraform.tfstate" \
            -backend-config="region=${{ env.AWS_REGION }}"
        working-directory: ./infra/terraform

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color --var region=${{ env.AWS_REGION }}
        working-directory: ./infra/terraform
        continue-on-error: true

      - name: Comment Terraform Plan Output
        uses: thollander/actions-comment-pull-request@v2.4.3
        with:
          message: |
            Terraform Plan Output:
            ```
            ${{ steps.plan.outputs.stdout }}
            ```
          mode: 'recreate'
